name: Deploy to Fly.io

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    name: Deploy app to Fly.io
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Fly.io CLI
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy to Fly.io
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          PORT: ${{ secrets.PORT }}
          MAX_ACTIVE_JOBS: ${{ secrets.MAX_ACTIVE_JOBS }}
          RATE_LIMIT_TTL: ${{ secrets.RATE_LIMIT_TTL }}
          REDIS_HOST: ${{ secrets.REDIS_HOST }}
          REDIS_PORT: ${{ secrets.REDIS_PORT }}
          BASIC_AUTH_USERNAME: ${{ secrets.BASIC_AUTH_USERNAME }}
          BASIC_AUTH_PASSWORD: ${{ secrets.BASIC_AUTH_PASSWORD }}
